import Head from "next/head";
import type { NextPage } from "next";

import {
  WalletDisconnectButton,
  WalletMultiButton,
} from "@solana/wallet-adapter-react-ui";

import { SendTxnButton } from "../components/SendTxnButton";
import { SendTxnGasless } from "../components/SendTxnGasless";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CandyPay SDK Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://candypay.fun">CandyPay</a>
        </h1>

        <div className={styles.walletButtons}>
          <WalletMultiButton />
          <WalletDisconnectButton />
        </div>
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <SendTxnButton />
          <SendTxnGasless />
        </div>
      </main>
    </div>
  );
};

export default Home;
